### ISSUE TITLE
No Built Executables

### ISSUE THREAD

**Issue by wendellmeset** [IonutParau/tpc_server#5]
For all those people who don't understand, I think you should add a pre-built version of the server in the latest stable releases. I am pretty sure you can do that with DartSDK, plus you mentioned it in the README.md.

**Comment by IonutParau** [comment]
People typically use actions for that

**Comment by IonutParau** [comment]
They autocompile the code, but I guess that could also be a stability issue so I guess I should make a tag for a version someday

**Comment by IonutParau** [comment]
Closing issue, will make a release soon
